db:
  image: postgres
  ports: 
    - "5432:5432"
web:
  build: .
  volumes:
    - ./salestock-test:/home/app/salestock-test
  environment:
    - SECRET_KEY_BASE=mynotsosecretkey
  ports: 
    - "80:80"
  links: 
    - db
  
